import glob
import os
import platform
import subprocess
import sys

import numpy as np
from setuptools import Extension, setup
from setuptools.command.build_ext import build_ext

import pyscipopt

# SCIP-SDP is compiled into the extension and uses the libscip bundled with the PySCIPOpt wheel,
# so that there is only one SCIP in the process. SCIP's headers come from SCIPOPTDIR.

# look for environment variable that specifies path to SCIP (only its headers are used)
scipoptdir = os.environ.get("SCIPOPTDIR", "").strip('"')
if not scipoptdir or not os.path.exists(os.path.join(scipoptdir, "include", "scip", "scip.h")):
    sys.exit("Set SCIPOPTDIR to a SCIP installation (for its headers) of the version used by PySCIPOpt.")
scip_includedir = os.path.abspath(os.path.join(scipoptdir, "include"))

# the headers must be of the same SCIP version as the libscip in the PySCIPOpt wheel
version = {}
with open(os.path.join(scip_includedir, "scip", "config.h")) as f:
    for line in f:
        if line.startswith("#define SCIP_VERSION_"):
            _, key, value = line.split()[:3]
            version[key] = value
model = pyscipopt.Model()
if (version.get("SCIP_VERSION_MAJOR"), version.get("SCIP_VERSION_MINOR")) != (str(model.getMajorVersion()), str(model.getMinorVersion())):
    sys.exit("SCIPOPTDIR has SCIP %s.%s, but PySCIPOpt uses SCIP %d.%d."
             % (version.get("SCIP_VERSION_MAJOR"), version.get("SCIP_VERSION_MINOR"), model.getMajorVersion(), model.getMinorVersion()))

# the libscip bundled with the PySCIPOpt wheel
pyscipoptdir = os.path.dirname(os.path.abspath(pyscipopt.__file__))
if platform.system() == "Darwin":
    libscipdir = os.path.join(pyscipoptdir, ".dylibs")
    libscip = glob.glob(os.path.join(libscipdir, "libscip.*.dylib"))
elif platform.system() == "Linux":
    libscipdir = os.path.join(os.path.dirname(pyscipoptdir), "pyscipopt.libs")
    libscip = glob.glob(os.path.join(libscipdir, "libscip*.so*"))
else:
    sys.exit("PySCIPSDP currently supports Linux and macOS.")
if len(libscip) != 1:
    sys.exit("Could not find the libscip of the PySCIPOpt wheel in %s." % libscipdir)
libscip = libscip[0]

# the SCIP-SDP sources: this repository, unless SCIPSDP_SOURCE points elsewhere
scipsdpdir = os.environ.get("SCIPSDP_SOURCE", "").strip('"')
if not scipsdpdir:
    scipsdpdir = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "..")
scipsdpdir = os.path.abspath(scipsdpdir)
if not os.path.exists(os.path.join(scipsdpdir, "src", "scipsdp", "cons_sdp.c")):
    sys.exit("Could not find the SCIP-SDP sources at %s; set SCIPSDP_SOURCE." % scipsdpdir)

scipsdp_sources = [os.path.join("scipsdp", f) for f in [
    "SdpVarmapper.c", "SdpVarfixer.c", "cons_sdp.c", "cons_savedsdpsettings.c", "cons_savesdpsol.c",
    "relax_sdp.c", "disp_sdpiterations.c", "disp_sdpavgiterations.c", "disp_sdpfastsettings.c",
    "disp_sdppenalty.c", "disp_sdpunsolved.c", "prop_sdpredcost.c", "branch_sdpmostfrac.c",
    "branch_sdpmostinf.c", "branch_sdpobjective.c", "branch_sdpinfobjective.c", "heur_sdpfracround.c",
    "heur_sdpinnerlp.c", "heur_sdpfracdiving.c", "heur_sdprand.c", "prop_sdpobbt.c", "prop_companalcent.c",
    "reader_cbf.c", "reader_sdpa.c", "table_relaxsdp.c", "table_slater.c", "scipsdpdefplugins.c"]]
scipsdp_sources += [os.path.join("sdpi", f) for f in [
    "sdpi.c", "sdpsolchecker.c", "solveonevarsdp.c", "lapack_interface.c", "sdpiclock.c"]]

include_dirs = [scip_includedir, os.path.join(scipsdpdir, "src"), os.path.join(scipsdpdir, "src", "scipsdp"), np.get_include()]
define_macros = []
libraries = []
extra_objects = []
extra_link_args = []

# SCIP-SDP's git hash file, normally generated by its build system (#included by scipsdpdefplugins.c)
gendir = os.path.join("build", "scipsdp")
os.makedirs(gendir, exist_ok=True)
try:
    githash = subprocess.check_output(["git", "-C", scipsdpdir, "rev-parse", "--short", "HEAD"], text=True).strip()
except (OSError, subprocess.CalledProcessError):
    githash = "unknown"
with open(os.path.join(gendir, "scipsdpgithash.c"), "w") as f:
    f.write('#define SCIPSDP_GITHASH "%s"\n' % githash)
include_dirs.append(gendir)

# SDP solver, as in SCIP-SDP's build system: none (default) or cbl (Clarabel)
sdps = os.environ.get("SDPS", "none")
if sdps == "cbl":
    clarabeldir = os.environ.get("CLARABEL_DIR", "").strip('"')
    clarabellib = os.path.join(clarabeldir, "rust_wrapper", "target", "release", "libclarabel_c.a")
    if not os.path.exists(clarabellib):
        sys.exit("SDPS=cbl needs CLARABEL_DIR pointing to a Clarabel.cpp checkout with the C library built (see README).")
    scipsdp_sources.append(os.path.join("sdpi", "sdpisolver_clarabel.c"))
    include_dirs.append(os.path.join(clarabeldir, "include"))
    define_macros.append(("FEATURE_SDP", None))
    extra_objects.append(clarabellib)
elif sdps == "none":
    scipsdp_sources.append(os.path.join("sdpi", "sdpisolver_none.c"))
else:
    sys.exit("SDPS must be none or cbl.")

# LAPACK and libscip
if platform.system() == "Darwin":
    extra_link_args += ["-framework", "Accelerate", "-liconv"]
    extra_objects.append(libscip)
    extra_link_args.append("-Wl,-rpath,@loader_path/../pyscipopt/.dylibs")
else:
    libraries += ["openblas", "m"]
    extra_link_args += ["-L" + libscipdir, "-l:" + os.path.basename(libscip), "-Wl,-rpath,$ORIGIN/../pyscipopt.libs"]

# enable debug mode if requested
extra_compile_args = []
if "--debug" in sys.argv:
    extra_compile_args.append("-UNDEBUG")
    sys.argv.remove("--debug")


class BuildExt(build_ext):
    """Refers to the libscip of the PySCIPOpt wheel through @rpath, as the wheel's copy has a placeholder install name."""

    def build_extension(self, ext):
        super().build_extension(ext)
        if platform.system() == "Darwin":
            installname = subprocess.check_output(["otool", "-D", libscip], text=True).split()[-1]
            subprocess.check_call(["install_name_tool", "-change", installname,
                                   "@rpath/" + os.path.basename(libscip), self.get_ext_fullpath(ext.name)])


from Cython.Build import cythonize

packagedir = os.path.join("src", "pyscipsdp")

# setuptools needs the sources below setup.py (otherwise the object files end up outside build/),
# so each SCIP-SDP source is compiled through a file in build/scipsdp that #includes it
sources = [os.path.join(packagedir, "scipsdp.pyx")]
for f in scipsdp_sources:
    wrapper = os.path.join(gendir, f.replace(os.sep, "_"))
    with open(wrapper, "w") as out:
        out.write('#include "%s"\n' % os.path.join(scipsdpdir, "src", f))
    sources.append(wrapper)

extensions = [
    Extension(
        "pyscipsdp.scipsdp",
        sources,
        include_dirs=include_dirs,
        define_macros=define_macros,
        libraries=libraries,
        extra_objects=extra_objects,
        extra_compile_args=extra_compile_args,
        extra_link_args=extra_link_args,
    )
]

# the .pxd files of the installed PySCIPOpt are cimported
extensions = cythonize(extensions, include_path=[os.path.dirname(pyscipoptdir)], compiler_directives={"language_level": 3})

setup(
    ext_modules=extensions,
    packages=["pyscipsdp"],
    package_dir={"pyscipsdp": packagedir},
    package_data={"pyscipsdp": ["scipsdp.pyx", "scipsdp.pxd"]},
    cmdclass={"build_ext": BuildExt},
)
